### ISSUE TITLE
Selection background too similar to rendered whitespace

### ISSUE THREAD

**Issue by 0xEAB** [LEFD/sweetdracula-monokai#1]
The background color applied to the current selection is too similar to the color used for rendered whitespace.
This renders the editor’s option`"editor.renderWhitespace": "selection"` pretty much unusable.

![screenshot](https://github.com/LEFD/sweetdracula-monokai/assets/15967408/f01b19d4-35c5-40ef-b892-33b9757223d9)
On my monitor the “tab arrow” is almost indistinguishable from the selection.

**Comment by LEFD** [comment]
Thanks a lot for your feedback! I will look into this.

**Comment by 0xEAB** [comment]
Thanks :tada:
